MAS_Sustainability/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using System.Data;
using System.IO;
using System.Web.UI;


namespace MAS_Sustainability.Controllers
{
    public class UserManagementController : Controller
    {
        // GET: UserManagement
        public ActionResult Edit(int id)
        {
            List<UserRegistrationModel> List_UserRegistration = new List<UserRegistrationModel>();
            MainModel mainModel = new MainModel();
            DataTable userDetailsDataTable = new DataTable();
            DB dbConn = new DB();

            using (MySqlConnection mySqlCon = dbConn.DBConnection())
            {
                mySqlCon.Open();
                String qry_listOfTokens = "SELECT UserName,UserType,UserID,UserEmail,UserMobile,UserDepartment,UserImage FROM users WHERE UserEmail = '" + Session["user"] + "'";
                MySqlDataAdapter mySqlDa = new MySqlDataAdapter(qry_listOfTokens, mySqlCon);
                mySqlDa.Fill(userDetailsDataTable);
            }

            for (int i = 0; i < userDetailsDataTable.Rows.Count; i++)
            {
                List_UserRegistration.Add(new UserRegistrationModel
                {
                    UserFullName = userDetailsDataTable.Rows[0][0].ToString(),
                    UserType = userDetailsDataTable.Rows[0][1].ToString(),
                    UserID = Convert.ToInt32(userDetailsDataTable.Rows[0][2]),
                    UserEmail = userDetailsDataTable.Rows[0][3].ToString(),
                    UserMobile = userDetailsDataTable.Rows[0][4].ToString(),
                    UserDepartment = userDetailsDataTable.Rows[0][5].ToString(),
                    UserImagePath = userDetailsDataTable.Rows[0][6].ToString()
                }
                );
            }

            if(userDetailsDataTable.Rows.Count == 1)
            {
                mainModel.LoggedUserName = userDetailsDataTable.Rows[0][0].ToString();
                mainModel.LoggedUserType = userDetailsDataTable.Rows[0][1].ToString();
                mainModel.LoggedUserID = Convert.ToInt32(userDetailsDataTable.Rows[0][2]);
                mainModel.UserImagePath = userDetailsDataTable.Rows[0][6].ToString();

                mainModel.ListUserRegistration = List_UserRegistration;
               
                return View(mainModel);
            }
            else
            {
                return View("Index");
            }



            
        }



        public ActionResult Index()
        {
            DataTable userDetailsDataTable = new DataTable();
            DataTable userListDataTable = new DataTable();
            MainModel mainModel = new MainModel();

            DataTable EmployeeCountDataTable = new DataTable();
            DataTable TokenManagerCountDataTable = new DataTable();
            DataTable DepartmentLeaderCountDataTable = new DataTable();
            DataTable FactoryManagementCountDataTable = new DataTable();

            // UserRegistrationModel userRegistrationModel = new UserRegistrationModel();

            List<UserRegistrationModel> List_UserRegistration = new List<UserRegistrationModel>();

            List<UserRegistrationModel> List_UseCount = new List<UserRegistrationModel>();

            DB dbConn = new DB();

            using (MySqlConnection mySqlCon = dbConn.DBConnection())
            {
                mySqlCon.Open();

                String qry_listOfTokens = "SELECT UserName,UserType,UserID,UserEmail,UserMobile,UserDepartment,UserImage FROM users WHERE UserEmail = '" + Session["user"] + "'";
                MySqlDataAdapter mySqlDa = new MySqlDataAdapter(qry_listOfTokens, mySqlCon);
                mySqlDa.Fill(userDetailsDataTable);


                String qry_listOfUsers = "SELECT * FROM users";
                MySqlDataAdapter mySqlData_UserList = new MySqlDataAdapter(qry_listOfUsers, mySqlCon);
                mySqlData_UserList.Fill(userListDataTable);

          
                String qry_get_count_Employees = "select count(UserID) FROM users WHERE UserType = 'Employee'";
                MySqlDataAdapter mySqlDataEmployee = new MySqlDataAdapter(qry_get_count_Employees,mySqlCon);
                mySqlDataEmployee.Fill(EmployeeCountDataTable);


                String qry_get_count_TokenManager = "select count(UserID) FROM users WHERE UserType = 'Token Manager'";
                MySqlDataAdapter mySqlDatTokenManager = new MySqlDataAdapter(qry_get_count_TokenManager, mySqlCon);
                mySqlDatTokenManager.Fill(TokenManagerCountDataTable);


                String qry_get_count_DepartmentLeader = "select count(UserID) FROM users WHERE UserType = 'Department Leader'";
                MySqlDataAdapter mySqlDataDepartmentLeader = new MySqlDataAdapter(qry_get_count_DepartmentLeader, mySqlCon);
                mySqlDataDepartmentLeader.Fill(DepartmentLeaderCountDataTable);


                mainModel.ArrFirstImagePath = new string[500];


            }

            if (Session["user"] == null || userDetailsDataTable.Rows[0][1].ToString() != ("Administrator"))
            {
                return RedirectToAction("Index", "Dashbord");
            }


            if (EmployeeCountDataTable.Rows.Count == 1)
            {

                List_UseCount.Add(new UserRegistrationModel
                {
                    EmployeeCount = Convert.ToInt32(EmployeeCountDataTable.Rows[0][0].ToString()),
                    TokenManagerCount = Convert.ToInt32(TokenManagerCountDataTable.Rows[0][0].ToString()),
                    DepartmentLeaderCount = Convert.ToInt32(DepartmentLeaderCountDataTable.Rows[0][0].ToString())
                });

                mainModel.UserContList = List_UseCount;


            }



            for (int i = 0; i < userListDataTable.Rows.Count; i++)
            {
               

                List_UserRegistration.Add(new UserRegistrationModel {

                    UserFullName = userListDataTable.Rows[i][1].ToString(),
                    UserType = userListDataTable.Rows[i][7].ToString(),
                    UserID = Convert.ToInt32(userListDataTable.Rows[i][0]),
                    UserEmail = userListDataTable.Rows[i][2].ToString(),
                    UserMobile = userListDataTable.Rows[i][3].ToString(),
                    UserDepartment = userListDataTable.Rows[i][6].ToString(),
                    UserImagePath = userListDataTable.Rows[i][8].ToString(),
                    UserValidity = userListDataTable.Rows[i][10].ToString()

                });

            }



            if (userDetailsDataTable.Rows.Count == 1)
            {
                mainModel.LoggedUserName = userDetailsDataTable.Rows[0][0].ToString();
                mainModel.LoggedUserType = userDetailsDataTable.Rows[0][1].ToString();
                mainModel.LoggedUserID = Convert.ToInt32(userDetailsDataTable.Rows[0][2]);
                mainModel.UserImagePath = userDetailsDataTable.Rows[0][6].ToString();

                mainModel.ListUserRegistration = List_UserRegistration;
                //ViewBag.UserImageVariable = mainModel;

                return View(mainModel);
            }
         
            else
            {
                return View()
;           }





        }

        public ActionResult UserProfile(int id)
        {

            List<UserRegistrationModel> List_UserDetails = new List<UserRegistrationModel>();
            List<UserRegistrationModel> List_UserRegistration = new List<UserRegistrationModel>();

            MainModel mainModel = new MainModel();
            DataTable userDetailsDataTable = new DataTable();
            DataTable LoggeduserDetailsDataTable = new DataTable();

            DataTable DataTablelastLoginDetails = new DataTable();

            DB dbConn = new DB();

            using (MySqlConnection mySqlCon = dbConn.DBConnection())
            {
                mySqlCon.Open();
                String qry_listOfUsers = "SELECT * FROM users WHERE UserID = @UserID";
                MySqlDataAdapter mySqlData_UserList = new MySqlDataAdapter(qry_listOfUsers, mySqlCon);
                mySqlData_UserList.SelectCommand.Parameters.AddWithValue("@UserID",id);
                mySqlData_UserList.Fill(userDetailsDataTable);

                String qry_lastlogDetails = "SELECT usr.UserID,ldt.FirstLoggedDate,ldt.FirstLoggedTime,ldt.LastLoggedDate,ldt.LastLoggedTime FROM login_details ldt,users usr WHERE usr.UserEmail = ldt.UserEmail and UserID = @UserID";
                MySqlDataAdapter mySqlData_lastlogDetails = new MySqlDataAdapter(qry_lastlogDetails, mySqlCon);
                mySqlData_lastlogDetails.SelectCommand.Parameters.AddWithValue("@UserID", id);
                mySqlData_lastlogDetails.Fill(DataTablelastLoginDetails);

                String qry_listOfTokens = "SELECT UserName,UserType,UserID,UserEmail,UserMobile,UserDepartment,UserImage FROM users WHERE UserEmail = '" + Session["user"] + "'";
                MySqlDataAdapter mySqlDa = new MySqlDataAdapter(qry_listOfTokens, mySqlCon);
                mySqlDa.Fill(LoggeduserDetailsDataTable);

            }

            if (LoggeduserDetailsDataTable.Rows.Count == 1)
            {
                mainModel.LoggedUserName = LoggeduserDetailsDataTable.Rows[0][0].ToString();
                mainModel.LoggedUserType = LoggeduserDetailsDataTable.Rows[0][1].ToString();
                mainModel.LoggedUserID = Convert.ToInt32(LoggeduserDetailsDataTable.Rows[0][2]);
                mainModel.UserImagePath = userDetailsDataTable.Rows[0][6].ToString();

            }

            if (userDetailsDataTable.Rows.Count == 1 && DataTablelastLoginDetails.Rows.Count == 1)
            {

                mainModel.UserProfileImagePath = userDetailsDataTable.Rows[0][8].ToString();

                List_UserDetails.Add(
                    new UserRegistrationModel {

MAS_Sustainability/Views/UserManagement/DepartmentLeadersInfoReportPreview.cshtml
@using MAS_Sustainability.Models;
@model MainModel
@{
    ViewBag.Title = "DepartmentLeadersInfoReportPreview";

}
<div class="content" id="panelDiv">
    <div class="page-inner">
        <div class="row justify-content-center">


            <div class="col-12 col-lg-10 col-xl-9">
                <div class="row align-items-center">
                    <div class="col">

                        <h4 class="page-title">Preview - List of Department Leaders</h4>
                    </div>
                    <div class="col-auto">

                        <a href="#" onclick="HTMLtoPDF()" class="btn btn-primary ml-2">
                            Download
                        </a>
                    </div>
                </div>
                <div class="page-divider"></div>

                <div class="row" id="HTMLtoPDF">
                    <div class="col-md-12">
                        <div class="card card-invoice">
                            <div class="card-header">

                                <h3 class="invoice-title">
                                    <img src="~/Content/images/MAS_logo.png" alt="" style="width:150px; height:35px">
                                </h3>

                                <div class="row">
                                    Industrial Maintainability & Safety Controlling System
                                </div>


                            </div>
                            <div class="card-body">
                                <div class="separator-solid"></div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="invoice-detail">
                                            <div class="invoice-top">
                                                <h3 class="title"><strong>List of Department Leaders</strong></h3>
                                            </div>
                                            <div class="invoice-item">
                                                <div class="table-responsive">
                                                    <table class="table table-striped">
                                                        <thead>
                                                            <tr>
                                                                <td class=""><strong>Name</strong></td>
                                                                <td class=""><strong>Department</strong></td>
                                                                <td class="text-right"><strong>Email</strong></td>
                                                                <td class=""><strong>Mobile</strong></td>
                                                            </tr>
                                                        </thead>
                                                        <tbody>

                                                            @foreach (var userDetailList in Model.ListUserRegistration)
                                                            {
                                                                if (@userDetailList.UserType == ("Department Leader"))
                                                                {



                                                                    <tr>
                                                                        <td class="">@userDetailList.UserFullName</td>
                                                                        <td class="">@userDetailList.UserDepartment</td>
                                                                        <td class="text-right">@userDetailList.UserEmail</td>
                                                                        <td class="">@userDetailList.UserMobile</td>
                                                                    </tr>
                                                                }

                                                            }


                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="separator-solid  mb-3"></div>
                                    </div>
                                </div>



                            </div>
                            <div class="card-footer">

                                <div class="separator-solid"></div>
                                <h6 class="text-uppercase mt-4 mb-3 fw-bold">
                                    Developped by THIRTYFIRST LANKA
                                </h6>

                            </div>
                        </div>
                    </div>
                </div>




            </div>


        </div>
    </div>
</div>

<script src="~/Content/assets/js/jspdf.js"></script>
<script src="~/Content/assets/js/jquery-2.1.3.js"></script>
<script src="~/Content/assets/js/pdfFromHTML.js"></script>

<script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/Content/assets/js/core/popper.min.js"></script>
<script src="~/Content/assets/js/core/bootstrap.min.js"></script>
<!-- jQuery UI -->
<script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<!-- Bootstrap Toggle -->
<script src="~/Content/assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
<!-- jQuery Scrollbar -->
<script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<!-- Atlantis JS -->
<script src="~/Content/assets/js/atlantis.min.js"></script>
<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="~/Content/assets/js/setting-demo.js"></script>

MAS_Sustainability/Views/UserManagement/Edit.cshtml
@using MAS_Sustainability.Models;
@model MainModel

@{
    Layout = "~/Views/Home/LayoutBody.cshtml";
}

@{
    ViewBag.Title = "Edit";
}

@foreach (var userInformation in Model.ListUserRegistration)
{
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                @*<h4 class="page-title">User Profile</h4>*@
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">
                                @*<div class="row row-nav-line">
                                        <ul class="nav nav-tabs nav-line nav-color-secondary" role="tablist">
                                            <li class="nav-item"> <a class="nav-link active show" data-toggle="tab" href="#home" role="tab" aria-selected="true">Timeline</a> </li>

                                        </ul>
                                    </div>*@
                                <h4 class="page-title">User Profile</h4>
                            </div>

                            <dv class="card-body">

                                @using (Html.BeginForm("UpdateUserProfile", "UserManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="tab-pane fade show active" id="home" role="tabpanel">
                                        <div class="card-body">

                                            <div class="row mt-3">
                                                <div class="col-md-12">
                                                    <div class="col-md-3">
                                                        <div class="input-file input-file-image">
                                                            <img class="img-upload-preview img-circle" width="120" height="120" src="@Url.Content(userInformation.UserImagePath)" alt="preview">
                                                            <input type="file" class="form-control form-control-file" id="UserImageFile" name="UserImage" accept="userimages/*" required="">
                                                            <label for="UserImageFile" class="badge badge-info">
                                                                <span class="btn-label">
                                                                    <i class="fa fa-file-image"></i>
                                                                </span>
                                                                Add Profile DB
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row mt-3">
                                                <div class="col-md-6">
                                                    <div class="form-group form-group-default">
                                                        <label>Name</label>
                                                        <input type="text" class="form-control" name="UserFullName" placeholder="Name" value="@userInformation.UserFullName">
                                                    </div>
                                                </div>

                                                <input type="hidden" name="UserID" value="@userInformation.UserID">

                                                <div class="col-md-6">
                                                    <div class="form-group form-group-default">
                                                        <label>Email</label>
                                                        <p>@userInformation.UserEmail</p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row mt-3">
                                                <div class="col-md-4">
                                                    <div class="form-group form-group-default">
                                                        <label>Birth Date</label>
                                                        <input type="text" class="form-control" id="datepicker" name="datepicker" value="" placeholder="Enter Your Birth Date">
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group form-group-default">
                                                        <label>Gender</label>
                                                        <select class="form-control" id="gender">
                                                            <option>Male</option>
                                                            <option>Female</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group form-group-default">
                                                        <label>Phone</label>
                                                        <input type="text" class="form-control" value="@userInformation.UserMobile" name="UserMobile" placeholder="Phone">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="text-right mt-3 mb-3">
                                                <button class="btn btn-success">Save</button>
                                                <button class="btn btn-danger">Reset</button>
                                            </div>

                                        </div>
                                    </div>

                                }

                                <hr />
                                <h4 class="page-title">Change Password</h4>

                                <div class="row mt-3">
                                    <div class="col-md-8">
                                        <div class="form-group form-group-default">
                                            <label>Current Password</label>
                                            <input type="password" class="form-control" id="datepicker" name="datepicker" value="" placeholder="Current Password">
                                            <div class="show-password">
                                                <i class="icon-eye"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="form-group form-group-default">
                                            <label>New Password</label>
                                            <input type="password" class="form-control" id="datepicker" name="datepicker" value="" placeholder="New Password">
                                            <div class="show-password">
                                                <i class="icon-eye"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="form-group form-group-default">
                                            <label>Confirm New Password</label>
                                            <input type="password" class="form-control" id="datepicker" name="datepicker" value="" placeholder="Confirm Password">
                                        </div>
                                    </div>

                                    <div class="col-md-4 text-right mt-3 mb-3">
                                        <button class="btn btn-info">Change Password</button>
                                    </div>
                                </div>

</div>
                    </div>



                    <div class="col-md-4">
                        <div class="card card-profile">
                            <div class="card-header" style="background-image: url('https://via.placeholder.com/325x215')">
                                <div class="profile-picture">
                                    <div class="avatar avatar-xl">
                                        <img src="@Url.Content(userInformation.UserImagePath)" alt="..." class="avatar-img rounded-circle">
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="user-profile text-center">
                                    <div class="name">@userInformation.UserFullName</div>
                                    <div class="job">@userInformation.UserDepartment</div>
                                    <div class="desc">@userInformation.UserType</div>
                                    <div class="social-media">
                                        <a class="btn btn-info btn-twitter btn-sm btn-link" href="#">
                                            <span class="btn-label just-icon"><i class="flaticon-twitter"></i> </span>
                                        </a>
                                        <a class="btn btn-danger btn-sm btn-link" rel="publisher" href="#">
                                            <span class="btn-label just-icon"><i class="flaticon-google-plus"></i> </span>
                                        </a>
                                        <a class="btn btn-primary btn-sm btn-link" rel="publisher" href="#">
                                            <span class="btn-label just-icon"><i class="flaticon-facebook"></i> </span>
                                        </a>
                                        <a class="btn btn-danger btn-sm btn-link" rel="publisher" href="#">
                                            <span class="btn-label just-icon"><i class="flaticon-dribbble"></i> </span>
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <div class="card-footer">
                                <div class="row user-stats text-center">
                                    <div class="col">
                                        <div class="number">125</div>
                                        <div class="title">Post</div>
                                    </div>
                                    <div class="col">
                                        <div class="number">25K</div>
                                        <div class="title">Followers</div>
                                    </div>
                                    <div class="col">
                                        <div class="number">134</div>
                                        <div class="title">Following</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
}



<script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/Content/assets/js/core/popper.min.js"></script>
<script src="~/Content/assets/js/core/bootstrap.min.js"></script>
<!-- jQuery UI -->
<script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<!-- Moment JS -->
<script src="~/Content/assets/js/plugin/moment/moment.min.js"></script><!-- DateTimePicker -->
<script src="~/Content/assets/js/plugin/datepicker/bootstrap-datetimepicker.min.js"></script>
<!-- Bootstrap Toggle -->
<script src="~/Content/assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
<!-- jQuery Scrollbar -->
<script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<!-- Atlantis JS -->
<script src="~/Content/assets/js/atlantis.min.js"></script>
<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="~/Content/assets/js/setting-demo.js"></script>
<script src="~/Content/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>



<script>
    $('#datepicker').datetimepicker({
        format: 'MM/DD/YYYY',
    });
</script>