MAS_Sustainability/Models/Token.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace MAS_Sustainability
{
    public class Token
    {
        public int TokenAuditID { get; set; }
        public String ProblemName { get; set; }
        public String ProblemCategory { get; set; }
        public String Location { get; set; }
        public String Description { get; set; }
        public String FirstImagePath { get; set; }
        public HttpPostedFileBase FirstImageFile { get; set; }
        public String SecondImagePath { get; set; }
        public HttpPostedFileBase SecondImageFile { get; set; }
        public int AttentionLevel { get; set; }
        public string UserName { get; set; }
        public string AddedDate { get; set; }

        public String ReparationDepartment { get; set; }
        public String SpecialActs { get; set; }
        public String SentDate { get; set; }


        public int no_of_token_rows_TokenManager { get; set; }

        public String TokenStatus { get; set; }

        public int ArrTokenAuditID { get; set; }
        public int ArrAttentionLevel { get; set; }
        public String ArrFirstImagePath { get; set; }
        public String ArrProblemName { get; set; }
        public String ArrLocation { get; set; }

        public String ArrUserName { get; set; }

        public int no_of_rows_side_bar { get; set; }

        public int no_of_tokens { get; set; }

        public String ArrTokenStatus { get; set; }

        public String LoggedUserNameSide { get; set; }

        public String SentUser { get; set; }




        //navodas part
        public String DeadLine { get; set; }
        public String RecievedStatus { get; set; }
        public String RepairStatus { get; set; }
        public String AddedUserName { get; set; }
        public String TokenManagerStatus { get; set; }
        public String HoriontalFirstImagePath { get; set; }
        public String CompleteStatus { get; set; }
        public String CompleteDate { get; set; }

        public String FinalVerificationStatus { get; set; }

        public int TokenManagerStatusPending { get; set; }

        public String CurrentDate { get; set; }


                    public String ProblemName_Expired {get;set;}
                    public String ProblemCategory_Expired {get;set;}
                    public String Location_Expired {get;set;}
                    public int AttentionLevel_Expired {get;set;}
                    public String UserName_Expired {get;set;}
                    public String TokenStatus_Expired {get;set;}
                    public int TokenAuditID_Expired {get;set;}
                    public String AddedDate_Expired {get;set;}
                    public String DeadLine_Expired {get;set;}
                    public String CompleteStatus_Expired {get;set;}
                    public String CompleteDate_Expired {get;set;}
                    public String FinalVerificationStatus_Expired {get;set;}



                    public String AddedUserName_Expired { get; set; }
                    public String SentDate_Expired { get; set; }
                    public String RecievedStatus_Expired { get; set; }
                    public String TokenManagerStatus_Expired { get; set; }



    }
}

MAS_Sustainability/Controllers/TokenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using System.Data;
using System.IO;
using MAS_Sustainability.Models;
using System.Net;

namespace MAS_Sustainability.Controllers
{
    public class TokenController : Controller
    {
        

        [HttpGet]
        // GET: Token
        public ActionResult Index()
        {
            MainModel finalItem = new MainModel();
            if (Session["user"] == null)
            {
                return RedirectToAction("Login", "UserLogin");
            }

            DB dbConn = new DB();
            DataTable dtblTokens = new DataTable();
            DataTable userDetailsDataTable = new DataTable();
            DataTable ForwardedTokeDataTable = new DataTable();

            DataTable ManagerStatus_pending_DataTable = new DataTable();


            MainModel mainModel = new MainModel();
            Token tokenModel = new Token();

            List<UserLogin> List_UserLogin = new List<UserLogin>();
            List<Token> List_Token = new List<Token>();
            List<Token> Token_List = new List<Token>();

            List<Token> TokenManagerPending_List = new List<Token>();


            using (MySqlConnection mySqlCon = dbConn.DBConnection())
            {
                mySqlCon.Open();
                string qry = "SELECT tka.TokenAuditID,tk.ProblemName,tk.Location,tk.AttentionLevel,usr.UserName,tkFlow.TokenManagerStatus FROM users usr,tokens tk, token_audit tka,token_flow tkFlow WHERE tk.TokenAuditID = tka.TokenAuditID AND tka.AddedUser = usr.UserEmail AND tk.TokenAuditID = tkFlow.TokenAuditID";  
                MySqlDataAdapter mySqlDA = new MySqlDataAdapter(qry,mySqlCon);
                mySqlDA.Fill(dtblTokens);



                String qry_forwared_tokens = "SELECT tka.TokenAuditID,tk.ProblemName,tk.Location,tk.AttentionLevel,usr.UserName,tkFlow.TokenManagerStatus,tkreview.SentUser " +
                    "FROM users usr,tokens tk, token_audit tka,token_flow tkFlow, token_review tkreview " +
                    "WHERE tk.TokenAuditID = tka.TokenAuditID AND tka.AddedUser = usr.UserEmail AND tk.TokenAuditID = tkFlow.TokenAuditID AND tk.TokenAuditID = tkreview.TokenAuditID and tkreview.Status != 'Accept'";

                MySqlDataAdapter mySqlDAForwardedTokens = new MySqlDataAdapter(qry_forwared_tokens,mySqlCon);
                mySqlDAForwardedTokens.Fill(ForwardedTokeDataTable);



                String qry_listOfTokens = "SELECT UserName,UserType,UserID,UserEmail,UserImage FROM users WHERE UserEmail = '" + Session["user"] + "'";
                MySqlDataAdapter mySqlDa = new MySqlDataAdapter(qry_listOfTokens, mySqlCon);
                mySqlDa.Fill(userDetailsDataTable);
                //DashbordController dashbord = new DashbordController();
                //finalItem.LoggedUserName = dashbord.setUserDetails().ToString();




            }

            for (int i = 0; i < dtblTokens.Rows.Count; i++)
            {
 
                List_Token.Add(new Token
                    { ProblemName = dtblTokens.Rows[i][1].ToString(),
                      Location = dtblTokens.Rows[i][2].ToString(),
                      AttentionLevel = Convert.ToInt32(dtblTokens.Rows[i][3]) ,
                      UserName = dtblTokens.Rows[i][4].ToString() ,
                      TokenStatus = dtblTokens.Rows[i][5].ToString(),
                      TokenAuditID = Convert.ToInt32(dtblTokens.Rows[i][0]),
                      //SentUser = dtblTokens.Rows[i][6].ToString()
                     }                                  
                );

            }

            for(int i = 0; i < ForwardedTokeDataTable.Rows.Count; i++)
            {
                Token_List.Add(new Token
                {
                    ProblemName = ForwardedTokeDataTable.Rows[i][1].ToString(),
                    Location = ForwardedTokeDataTable.Rows[i][2].ToString(),
                    AttentionLevel = Convert.ToInt32(ForwardedTokeDataTable.Rows[i][3]),
                    UserName = ForwardedTokeDataTable.Rows[i][4].ToString(),
                    TokenStatus = ForwardedTokeDataTable.Rows[i][5].ToString(),
                    TokenAuditID = Convert.ToInt32(ForwardedTokeDataTable.Rows[i][0]),
                    SentUser = ForwardedTokeDataTable.Rows[i][6].ToString()

                }
                );
            }

            if (userDetailsDataTable.Rows.Count == 1)
            {
                mainModel.LoggedUserName = userDetailsDataTable.Rows[0][0].ToString();
                mainModel.LoggedUserType = userDetailsDataTable.Rows[0][1].ToString();
                mainModel.LoggedUserID = Convert.ToInt32(userDetailsDataTable.Rows[0][2]);
                mainModel.LoggedUserEmail = userDetailsDataTable.Rows[0][3].ToString();
                mainModel.UserImagePath = userDetailsDataTable.Rows[0][4].ToString();
            }


            if (ManagerStatus_pending_DataTable.Rows.Count == 1)
            {
                /*TokenManagerPending_List.Add(new Token
                {
                   TokenManagerStatusPending = 4/*Convert.ToInt32(ManagerStatus_pending_DataTable.Rows[0][0].ToString())*/
                //});

                //mainModel.TokenMaagerStatusPendingList = TokenManagerPending_List;

                mainModel.TokenManagerStatusPending = Convert.ToInt32(ManagerStatus_pending_DataTable.Rows[0][0].ToString());
            }
            

            mainModel.ListToken = List_Token;
            mainModel.ListUserLogin = List_UserLogin;
            mainModel.TokenList = Token_List;
            mainModel.TokenManagerStatusPending = TokenManagerPendingSattusCount();



            return View(mainModel);
        }


        public static int TokenManagerPendingSattusCount()
        {
            DataTable ManagerStatus_pending_DataTable = new DataTable();
            MainModel mainModel = new MainModel();
            DB dbConn = new DB();

            using (MySqlConnection mySqlCon = dbConn.DBConnection())
            {
                String qry_count_TokenManager_status_Pending = "SELECT COUNT(TokenFlowID) FROM token_flow WHERE TokenManagerStatus = 'Pending'";
                MySqlDataAdapter mySqlDa_count_TokenManager_status_Pending = new MySqlDataAdapter(qry_count_TokenManager_status_Pending, mySqlCon);
                mySqlDa_count_TokenManager_status_Pending.Fill(ManagerStatus_pending_DataTable);
            }

            if (ManagerStatus_pending_DataTable.Rows.Count == 1)
            {
                mainModel.TokenManagerStatusPending = Convert.ToInt32(ManagerStatus_pending_DataTable.Rows[0][0].ToString());
            }



                return mainModel.TokenManagerStatusPending;
        }





        // GET: Token/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Token/Create
        public ActionResult Add()
        {
            DB dbConn = new DB();
            DataTable userDetailsDataTable = new DataTable();
            MainModel mainModel = new MainModel();
            using (MySqlConnection mySqlCon = dbConn.DBConnection())
            {
                String qry_listOfTokens = "SELECT UserName,UserType,UserID,UserImage FROM users WHERE UserEmail = '" + Session["user"] + "'";
                MySqlDataAdapter mySqlDa = new MySqlDataAdapter(qry_listOfTokens, mySqlCon);
                mySqlDa.Fill(userDetailsDataTable);
            }

            if (userDetailsDataTable.Rows.Count == 1)
            {
                mainModel.LoggedUserName = userDetailsDataTable.Rows[0][0].ToString();
                mainModel.LoggedUserType = userDetailsDataTable.Rows[0][1].ToString();
                mainModel.LoggedUserID = Convert.ToInt32(userDetailsDataTable.Rows[0][2]);
                mainModel.UserImagePath = userDetailsDataTable.Rows[0][3].ToString();
            }


            return View(mainModel);
        }

        // POST: Token/Create
        [HttpPost]
        public ActionResult Add(Token tokenModel)
        {

        
            DataTable userDetailsDataTable = new DataTable();
            MainModel mainModel = new MainModel();



            //Image 01
            string first_name_of_file = Path.GetFileNameWithoutExtension(tokenModel.FirstImageFile.FileName);
            string extension1 = Path.GetExtension(tokenModel.FirstImageFile.FileName);
            first_name_of_file = first_name_of_file + DateTime.Now.ToString("yymmssfff") +extension1;
            tokenModel.FirstImagePath = "~/Image/" +first_name_of_file;
            first_name_of_file = Path.Combine(Server.MapPath("~/Image/"), first_name_of_file);
            tokenModel.FirstImageFile.SaveAs(first_name_of_file);

            String imgPath1 = tokenModel.FirstImagePath;



            //Image 02
            string second_name_of_file = Path.GetFileNameWithoutExtension(tokenModel.SecondImageFile.FileName);
            string extension2 = Path.GetExtension(tokenModel.SecondImageFile.FileName);
            second_name_of_file = second_name_of_file + DateTime.Now.ToString("yymmssfff") + extension2;
            tokenModel.SecondImagePath = "~/Image/" + second_name_of_file;
            second_name_of_file = Path.Combine(Server.MapPath("~/Image/"), second_name_of_file);
            tokenModel.SecondImageFile.SaveAs(second_name_of_file);

            String imgPath2 = tokenModel.SecondImagePath;




            String AddedUser = Session["user"].ToString();


            DB dbConn = new DB();
            using (MySqlConnection mySqlCon = dbConn.DBConnection())
            {

                mySqlCon.Open();
                // String qry = "INSERT INTO token_audit(AddedUser,Category,AddedDate)VALUES(@AddedUser,@Category,NOW())";



                MySqlCommand mySqlCmd_TokenAudit = new MySqlCommand("Proc_Store_TokenAudit", mySqlCon);
                mySqlCmd_TokenAudit.CommandType = CommandType.StoredProcedure;

MAS_Sustainability/Views/Token/ExpiredTokens.cshtml
@using MAS_Sustainability.Models
@model MainModel
@{
    ViewBag.Title = "ExpiredTokens";
    Layout = "~/Views/Home/LayoutBody.cshtml";
}

@if (Model != null)
{
    <div class="main-panel">
        <div class="content">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <div id="basic-datatables_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                            <div class="row">
                                <div class="col-sm-12 col-md-6">

                                </div>

                            </div>
                            <div class="row">
                                <div class="col-sm-12">

                                    <div class="card">
                                        <div class="card-header">
                                            <div class="d-flex align-items-center">
                                                <h4 class="card-title">Expired Tokens</h4>
                                            </div>
                                        </div>
                                        <div class="card-body">


                                            <div class="table-responsive">
                                                <table id="add-row" class="display table table-striped table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th>Problem Name</th>
                                                            <th>Location</th>
                                                            <th style="width:50px">Category</th>
                                                            <th>Reparation</th>
                                                            <th>Deadline</th>
                                                            <th>Action</th>

                                                        </tr>
                                                    </thead>



                                                    <tbody>

                                                        @foreach (var no_of_tokens_expired in Model.ExpiredTokensList)
                                                        {
                                                            if (@no_of_tokens_expired.TokenStatus_Expired != ("Pending") && @no_of_tokens_expired.CompleteStatus_Expired != ("Completed"))
                                                            {

                                                                <tr>
                                                                    <td style="color:red; font-style:bold"><b>@no_of_tokens_expired.ProblemName_Expired</b></td>
                                                                    <td style="color:red; font-style:bold"><b>@no_of_tokens_expired.Location_Expired</b></td>
                                                                    <td style="width:50px;color:red; font-style:bold"><b>@no_of_tokens_expired.ProblemCategory_Expired</b></td>
                                                                    <td style="color:red; font-style:bold"><b>@no_of_tokens_expired.TokenStatus_Expired</b></td>
                                                                    <td style="color:red; font-style:bold"><b>@no_of_tokens_expired.DeadLine_Expired</b></td>
                                                                    <td> <span class="badge badge-success"><a href="@Url.Action("ViewRepairation", "Token", new { @id = no_of_tokens_expired.TokenAuditID_Expired })"><strong>View</strong></a></span></td>
                                                                </tr>

                                                            }

                                                        }



                                                    </tbody>


                                                </table>
                                            </div>
                                        </div>
                                    </div>


                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 
}




    <script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
    <script src="~/Content/assets/js/core/popper.min.js"></script>
    <script src="~/Content/assets/js/core/bootstrap.min.js"></script>
    <!-- jQuery UI -->
    <script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
    <script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
    <!-- Bootstrap Toggle -->
    <script src="~/Content/assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
    <!-- jQuery Scrollbar -->
    <script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
    <!-- Datatables -->
    <script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
    <!-- Atlantis JS -->
    <script src="~/Content/assets/js/atlantis.min.js"></script>
    <!-- Atlantis DEMO methods, don't include it in your project! -->
    <script src="~/Content/assets/js/setting-demo2.js"></script>









    <script>
        $(document).ready(function () {
            $('#basic-datatables').DataTable({


            });




        });
    </script>

MAS_Sustainability/Views/Token/ProcessingTokensPreView.cshtml
@using MAS_Sustainability.Models;
@model MainModel
@{
    ViewBag.Title = "ProcessingTokensPreView";
}

<div class="content" id="panelDiv">
    @if (Model != null)
    {
        <div class="page-inner">
            <div class="row justify-content-center">


                <div class="col-12 col-lg-10 col-xl-9">
                    <div class="row align-items-center">
                        <div class="col">

                            <h4 class="page-title">Preview - My Processing Problems</h4>
                        </div>
                        <div class="col-auto">

                            <a href="#" onclick="HTMLtoPDF()" class="btn btn-primary ml-2">
                                Download
                            </a>
                        </div>
                    </div>
                    <div class="page-divider"></div>

                    <div class="row" id="HTMLtoPDF">
                        <div class="col-md-12">
                            <div class="card card-invoice">
                                <div class="card-header">

                                    <h3 class="invoice-title">
                                        <img src="~/Content/images/MAS_logo.png" alt="" style="width:150px; height:35px">
                                    </h3>

                                    <div class="row">
                                        Industrial Maintainability & Safety Controlling System
                                    </div>


                                </div>
                                <div class="card-body">
                                    <div class="separator-solid"></div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="invoice-detail">
                                                <div class="invoice-top">
                                                    <h3 class="title"><strong>My Processing Problems</strong></h3>
                                                </div>
                                                <div class="invoice-item">
                                                    <div class="table-responsive">
                                                        <table class="table table-striped">
                                                            <thead>
                                                                <tr>
                                                                    <th>Problem Name</th>
                                                                    <th>Location</th>
                                                                    <th style="width:50px">Category</th>
                                                                    <th>Reparation</th>
                                                                    <th>Deadline</th>
                                                                </tr>
                                                            </thead>
                                                            <tbody>


                                                                @foreach (var no_of_tokens_expired in Model.ExpiredTokensList)
                                                                {
                                                                    if (@no_of_tokens_expired.TokenStatus_Expired != ("Pending") && @no_of_tokens_expired.CompleteStatus_Expired != ("Completed"))
                                                                    {

                                                                        <tr>
                                                                            <td style="color:red; font-style:bold"><b style="color:red">@no_of_tokens_expired.ProblemName_Expired</b></td>
                                                                            <td style="color:red; font-style:bold"><b style="color:red">@no_of_tokens_expired.Location_Expired</b></td>
                                                                            <td style="width:50px;color:red; font-style:bold"><b style="color:red">@no_of_tokens_expired.ProblemCategory_Expired</b></td>
                                                                            <td style="color:red; font-style:bold"><b style="color:red">@no_of_tokens_expired.TokenStatus_Expired</b></td>
                                                                            <td style="color:red; font-style:bold"><b style="color:red">@no_of_tokens_expired.DeadLine_Expired</b></td>
                                                                        </tr>

                                                                    }

                                                                }


                                                                @foreach (var no_of_tokens in Model.ListToken)
                                                                {
                                                                    if (@no_of_tokens.TokenStatus != ("Pending") && @no_of_tokens.CompleteStatus != ("Completed"))
                                                                    {

                                                                        <tr>
                                                                            <td>@no_of_tokens.ProblemName</td>
                                                                            <td>@no_of_tokens.Location</td>
                                                                            <td style="width:50px">@no_of_tokens.ProblemCategory</td>
                                                                            <td>@no_of_tokens.TokenStatus</td>
                                                                            <td>@no_of_tokens.DeadLine</td>
                                                                        </tr>

                                                                    }

                                                                }


                                                            </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="separator-solid  mb-3"></div>
                                        </div>
                                    </div>



                                </div>
                                <div class="card-footer">

                                    <div class="separator-solid"></div>
                                    <h6 class="text-uppercase mt-4 mb-3 fw-bold">
                                        Developped by THIRTYFIRST LANKA
                                    </h6>

                                </div>
                            </div>
                        </div>
                    </div>




                </div>


            </div>
        </div>
    }
    </div>

<script src="~/Content/assets/js/jspdf.js"></script>
<script src="~/Content/assets/js/jquery-2.1.3.js"></script>
<script src="~/Content/assets/js/pdfFromHTML.js"></script>

<script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/Content/assets/js/core/popper.min.js"></script>
<script src="~/Content/assets/js/core/bootstrap.min.js"></script>
<!-- jQuery UI -->
<script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<!-- Bootstrap Toggle -->
<script src="~/Content/assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js"></script>
<!-- jQuery Scrollbar -->
<script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<!-- Atlantis JS -->
<script src="~/Content/assets/js/atlantis.min.js"></script>
<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="~/Content/assets/js/setting-demo.js"></script>

MAS_Sustainability/Views/Token/View1.cshtml
@using MultipleModelInOneView;